### ISSUE TITLE
Fix Permissions (option 14) keeps failing on fresh install of Debian.

### ISSUE THREAD

**Issue by juanhaywood** [openhab/openhabian#1369]
## Issue information:
Fix Permissions (option 14) keeps failing on fresh install of Debian. I've tried both the interactive and unattended installation options, and it fails with both. The main error seems to be as follows: "FAILED (openhab server mounts)"

## Debug information:
Full Debug log:

```
[?1049l[23;0;0t+ choice2='14 | Fix Permissions'
+ '[' 0 -eq 1 ']'
+ '[' 1 -eq 255 ']'
+ wait_for_apt_to_finish_update
++ timestamp
++ date +%F_%T_%Z
+ echo -n '2021-01-02_17:57:14_SAST [openHABian] Updating Linux package information... '
2021-01-02_17:57:14_SAST [openHABian] Updating Linux package information... + [[ -z 2158 ]]
+ tail --pid=2158 -f /dev/null
+ echo OK
OK
+ case "$choice2" in
+ permissions_corrections
+ local gpioDir=/sys/devices/platform/soc
+ groups=("audio" "bluetooth" "dialout" "gpio" "tty")
+ local groups
+ openhabFolders=("/etc/openhab2" "/var/lib/openhab2" "/var/log/openhab2" "/usr/share/openhab2")
+ local openhabFolders
+ local openhabHome=/var/lib/openhab2
++ timestamp
++ date +%F_%T_%Z
+ echo -n '2021-01-02_17:57:14_SAST [openHABian] Applying file permissions recommendations... '
2021-01-02_17:57:14_SAST [openHABian] Applying file permissions recommendations... + openhab_is_installed
+ openhab2_is_installed
++ cut '-d ' -f2
++ grep Status
++ dpkg -s openhab2
+ [[ '' == \i\n\s\t\a\l\l ]]
+ return 1
+ openhab3_is_installed
++ cut '-d ' -f2
++ grep Status
++ dpkg -s openhab
+ [[ install == \i\n\s\t\a\l\l ]]
+ return 0
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*audio:' /etc/group
+ cond_redirect usermod --append --groups audio openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups audio openhab \033[39;49;00m'

[90;01m$ usermod --append --groups audio openhab [39;49;00m
+ usermod --append --groups audio openhab
+ return 0
+ cond_redirect usermod --append --groups audio openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups audio openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups audio openhabian [39;49;00m
+ usermod --append --groups audio openhabian
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*bluetooth:' /etc/group
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*dialout:' /etc/group
+ cond_redirect usermod --append --groups dialout openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups dialout openhab \033[39;49;00m'

[90;01m$ usermod --append --groups dialout openhab [39;49;00m
+ usermod --append --groups dialout openhab
+ return 0
+ cond_redirect usermod --append --groups dialout openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups dialout openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups dialout openhabian [39;49;00m
+ usermod --append --groups dialout openhabian
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*gpio:' /etc/group
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*tty:' /etc/group
+ cond_redirect usermod --append --groups tty openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups tty openhab \033[39;49;00m'

[90;01m$ usermod --append --groups tty openhab [39;49;00m
+ usermod --append --groups tty openhab
+ return 0
+ cond_redirect usermod --append --groups tty openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups tty openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups tty openhabian [39;49;00m
+ usermod --append --groups tty openhabian
+ return 0
+ cond_redirect usermod --append --groups openhab openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups openhab openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups openhab openhabian [39;49;00m
+ usermod --append --groups openhab openhabian
+ return 0
+ cond_redirect chown openhab:openhab /srv /srv/README.txt /opt
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chown openhab:openhab /srv /srv/README.txt /opt \033[39;49;00m'

[90;01m$ chown openhab:openhab /srv /srv/README.txt /opt [39;49;00m
+ chown openhab:openhab /srv /srv/README.txt /opt
chown: cannot access '/srv/README.txt': No such file or directory
+ return 1
+ echo 'FAILED (openhab server mounts)'
FAILED (openhab server mounts)
+ return 1
+ '[' 1 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "10 | Apply Improvements"\n\nPlease try again. If the error persists, please read /opt/openhabian/docs/openhabian-DEBUG.md or https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md how to proceed.' 14 80
```

## System information:
OS: Debian
HW: Hyper-v VM

`cat /etc/os-release` output:
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

`uname -m` output: 
i686

**Comment by juanhaywood** [comment]
Just tested on a clean installation of Ubuntu, and have the exact same issue. Full installation debug logs attached.
[OH3Ubu.log](https://github.com/openhab/openhabian/files/5760514/OH3Ubu.log)

**Comment by mstormi** [comment]
https://github.com/openhab/openhabian/commit/18bb3de55c8afc4e4079adc8a87a3861a174e5df should fix it
pls validate

**Comment by juanhaywood** [comment]
Tested, and the issue persists. Full log from clean Debian installation attached.

[OH3Deb.log](https://github.com/openhab/openhabian/files/5763858/OH3Deb.log)

**Comment by juanhaywood** [comment]
@mstormi I don't seem to be able to reopen the issue

**Comment by juanhaywood** [comment]
$ chown --recursive openhab:openhab /etc/openhab2 /var/lib/openhab2 /var/log/openhab2 /usr/share/openhab2
+ chown --recursive openhab:openhab /etc/openhab2 /var/lib/openhab2 /var/log/openhab2 /usr/share/openhab2
chown: cannot access '/etc/openhab2': No such file or directory
chown: cannot access '/var/lib/openhab2': No such file or directory
chown: cannot access '/var/log/openhab2': No such file or directory
chown: cannot access '/usr/share/openhab2': No such file or directory
+ return 1
+ echo 'FAILED (openhab folders)'
FAILED (openhab folders)

**Comment by mstormi** [comment]
Thing is I don't have x86 Debian to test against.
I actually DID fix your issue but there's others.
Can you please find out which of the directories below is not there ?

```
$ chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba
+ chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba
+ return 1
+ echo 'FAILED (samba and 3rd party logdir)'

**Comment by mstormi** [comment]
> $ chown --recursive openhab:openhab /etc/openhab2 /var/lib/openhab2 /var/log/openhab2 /usr/share/openhab2

You have changed the branch.
You start in openHAB3 branch (see line 335 of your debug log) and must not change to master or stable.

**Comment by juanhaywood** [comment]
I've not changed anything. From a clean Debian install, I simply pull openhabian via git, then perform the unattended installation. I'll try to manually set the branch to openhab3 before initiating the unattended installation.

**Comment by WolfgangSn** [comment]
> Thing is I don't have x86 Debian to test against.
> I actually DID fix your issue but there's others.
> Can you please find out which of the directories below is not there ? Are Samba and ZRAM installed ?
> 
ZRAM is not installed on x86 Debian systems as it is only allowed to be installed on is_arm systems using openhabian-config.

**Comment by juanhaywood** [comment]
Only commands I now ran:

```
1. sudo bash
2. apt-get install git
3. git clone -b openHAB3 https://github.com/openhab/openhabian.git /opt/openhabian
4. ln -s /opt/openhabian/openhabian-setup.sh /usr/local/bin/openhabian-config
5. cp /opt/openhabian/openhabian.conf.dist /etc/openhabian.conf
6. sudo nano /etc/openhabian.conf //debig=maximum
7. openhabian-config //to check the selected branch. It's on openHAB3 by default. Changed nothing and simply exited openhabian-config.
8. openhabian-config unattended
```

Get error on log line 6113: FAILED (samba and 3rd party logdir)

Next I run:
`openhabian-config //confirmed it is still on openHAB3 branch, then manually ran command 14 - Fix permissions. `

Still results in "FAILED (samba and 3rd party logdir)"

Full log for everything above attached: 
[OH3DebNew.log](https://github.com/openhab/openhabian/files/5764386/OH3DebNew.log)

**Comment by mstormi** [comment]
you dont need to install from scratch just use menu 14
I have not changed the code yet so you got what you got last time.
List dirs as I asked you to please

**Comment by juanhaywood** [comment]
Sorry, missed that message.
Exists: /var/log/samba /var/log/unattended-upgrades 
Doesn't exist: /opt/zram/log.bind/samba

**Comment by mstormi** [comment]
arrgh why can't you guys not just simply use a RPi ...

**Comment by mstormi** [comment]
please try the fixPerms branch
set `clonebranch=fixPerms` in `openhabian.conf`, double-check on start, then menu 14

**Comment by mstormi** [comment]
sorry I got interrupted and failed to upload the changes. Now they are so pls try with the fixPerms branch now.

**Comment by juanhaywood** [comment]
I set clonebranch=fixPerm, but the error persists :(

```
++ whiptail --title 'Welcome to the openHABian Configuration Tool [fixPerms]patchday-20210104-1091(ba08671)' --menu 'Apply Improvements' 13 116 6 --cancel-button Back --ok-button Execute '11 | Packages' 'Install needed and recommended system packages' '12 | Bash&Vim Settings' 'Update customized openHABian settings for bash, vim and nano' '13 | System Tweaks' 'Add /srv mounts and update settings typical for openHAB' '14 | Fix Permissions' 'Update file permissions of commonly used files and folders' '15 | FireMotD' 'Upgrade the program behind the system overview on SSH login' '16 | Samba' 'Install the Samba file sharing service and set up openHAB shares'
[?1049h[22;0;0t[1;63r[4l[?25l(B[m[37m[40m[1;63r[H[2J[1;1H[1m[37m[44m                                                                                                                                                                                                                                             [2;1H                                                                                                                                                                                                                                             [3;1H                                                                                                                                                                                                                                             [4;1H                                                                                                                                                                                                                                             [5;1H                                                                                                                                                                                                                                             [6;1H                                                                                                                                                                                                                                             [7;1H                                                                                                                                                                                                                                             [8;1H                                                                                                                                                                                                                                             [9;1H                                                                                                                                                                                                                                             [10;1H                                                                                                                                                                                                                                             [11;1H                                                                                                                                                                                                                                             [12;1H                                                                                                                                                                                                                                             [13;1H                                                                                                                                                                                                                                             [14;1H                                                                                                                                                                                                                                             [15;1H                                                                                                                                                                                                                                             [16;1H                                                                                                                                                                                                                                             [17;1H                                                                                                                                                                                                                                             [18;1H                                                                                                                                                                                                                                             [19;1H                                                                                                                                                                                                                                             [20;1H                                                                                                                                                                                                                                             [21;1H                                                                                                                                                                                                                                             [22;1H                                                                                                                                                                                                                                             [23;1H                                                                                                                                                                                                                                             [24;1H                                                                                                                                                                                                                                             [25;1H                                                                                                                                                                                                                                             [26;1H                                                                                                                                                                                                                                             [27;1H                                                                                                                                                                                                                                             [28;1H                                                                                                                                                                                                                                             [29;1H                                                                                                                                                                                                                                             [30;1H                                                                                                                                                                                                                                             [31;1H                                                                                                                                                                                                                                             [32;1H                                                                                                                                                                                                                                             [33;1H                                                                                                                                                                                                                                             [34;1H                                                                                                                                                                                                                                             [35;1H                                                                                                                                                                                                                                             [36;1H                                                                                                                                                                                                                                             [37;1H                                                                                                                                                                                                                                             [38;1H                                                                                                                                                                                                                                             [39;1H                                                                                                                                                                                                                                             [40;1H                                                                                                                                                                                                                                             [41;1H                                                                                                                                                                                                                                             [42;1H                                                                                                                                                                                                                                             [43;1H                                                                                                                                                                                                                                             [44;1H                                                                                                                                                                                                                                             [45;1H                                                                                                                                                                                                                                             [46;1H                                                                                                                                                                                                                                             [47;1H                                                                                                                                                                                                                                             [48;1H                                                                                                                                                                                                                                             [49;1H                                                                                                                                                                                                                                             [50;1H                                                                                                                                                                                                                                             [51;1H                                                                                                                                                                                                                                             [52;1H                                                                                                                                                                                                                                             [53;1H                                                                                                                                                                                                                                             [54;1H                                                                                                                                                                                                                                             [55;1H                                                                                                                                                                                                                                             [56;1H                                                                                                                                                                                                                                             [57;1H                                                                                                                                                                                                                                             [58;1H                                                                                                                                                                                                                                             [59;1H                                                                                                                                                                                                                                             [60;1H                                                                                                                                                                                                                                             [61;1H                                                                                                                                                                                                                                             [62;1H                                                                                                                                                                                                                                             [63;1H                                                                                                                                                                                                                                            [63;236H [4h [4l[1;1H[26;61H(B[m[30m[47m┌────────────┤ [31mWelcome to the openHABian Configuration Tool [fixPerms]patchday-20210104-1091(ba08671)[30m ├────────────┐[27;61H│                                                                                                                  │[1m[37m[40m [28;61H(B[m[30m[47m│             [37m[41m11 | Packages          Install needed and recommended system packages                  [30m[47m              │[1m[37m[40m [29;61H(B[m[30m[47m│             12 | Bash&Vim Settings Update customized openHABian settings for bash, vim and nano                  │[1m[37m[40m [30;61H(B[m[30m[47m│             13 | System Tweaks     Add /srv mounts and update settings typical for openHAB                       │[1m[37m[40m [31;61H(B[m[30m[47m│             14 | Fix Permissions   Update file permissions of commonly used files and folders                    │[1m[37m[40m [32;61H(B[m[30m[47m│             15 | FireMotD          Upgrade the program behind the system overview on SSH login                   │[1m[37m[40m [33;61H(B[m[30m[47m│             16 | Samba             Install the Samba file sharing service and set up openHAB shares              │[1m[37m[40m [34;61H(B[m[30m[47m│                                                                                                                  │[1m[37m[40m [35;61H(B[m[30m[47m│                                                                                                                  │[1m[37m[40m [36;61H(B[m[30m[47m│                                 <Execute>                                <Back>                                  │[1m[37m[40m [37;61H(B[m[30m[47m│                                                                                                                  │[1m[37m[40m [38;61H(B[m[30m[47m└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘[1m[37m[40m [39;62H                                                                                                                    [28;75H(B[m[30m[47m11 | Packages          Install needed and recommended system packages                  [29;75H[37m[41m12 | Bash&Vim Settings Update customized openHABian settings for bash, vim and nano    [29;75H[30m[47m12 | Bash&Vim Settings Update customized openHABian settings for bash, vim and nano    [30;75H[37m[41m13 | System Tweaks     Add /srv mounts and update settings typical for openHAB         [30;75H[30m[47m13 | System Tweaks     Add /srv mounts and update settings typical for openHAB         [31;75H[37m[41m14 | Fix Permissions   Update file permissions of commonly used files and folders      [31;75H[30m[47m14 | Fix Permissions   Update file permissions of commonly used files and folders      [32;75H[37m[41m15 | FireMotD          Upgrade the program behind the system overview on SSH login     [32;75H[A14 | Fix Permissions   Update file permissions of commonly used files and folders      [32;75H[30m[47m15 | FireMotD          Upgrade the program behind the system overview on SSH login     [31;75H[?12l[?25h[63;1H[37m[40m(B[m[39;49m
[K
[?1049l[23;0;0t+ choice2='14 | Fix Permissions'
+ '[' 0 -eq 1 ']'
+ '[' 1 -eq 255 ']'
+ wait_for_apt_to_finish_update
++ timestamp
++ date +%F_%T_%Z
+ echo -n '2021-01-04_23:00:30_CET [openHABian] Updating Linux package information... '
2021-01-04_23:00:30_CET [openHABian] Updating Linux package information... + [[ -z 17086 ]]
+ tail --pid=17086 -f /dev/null
+ echo OK
OK
+ case "$choice2" in
+ permissions_corrections
+ local gpioDir=/sys/devices/platform/soc
+ groups=("audio" "bluetooth" "dialout" "gpio" "tty")
+ local groups
+ openhabFolders=("/etc/openhab" "/var/lib/openhab" "/var/log/openhab" "/usr/share/openhab")
+ local openhabFolders
+ local openhabHome=/var/lib/openhab
++ timestamp
++ date +%F_%T_%Z
+ echo -n '2021-01-04_23:00:30_CET [openHABian] Applying file permissions recommendations... '
2021-01-04_23:00:30_CET [openHABian] Applying file permissions recommendations... + openhab_is_installed
+ openhab2_is_installed
++ cut '-d ' -f2
++ grep Status
++ dpkg -s openhab2
+ [[ '' == \i\n\s\t\a\l\l ]]
+ return 1
+ openhab3_is_installed
++ cut '-d ' -f2
++ grep Status
++ dpkg -s openhab
+ [[ install == \i\n\s\t\a\l\l ]]
+ return 0
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*audio:' /etc/group
+ cond_redirect usermod --append --groups audio openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups audio openhab \033[39;49;00m'

[90;01m$ usermod --append --groups audio openhab [39;49;00m
+ usermod --append --groups audio openhab
+ return 0
+ cond_redirect usermod --append --groups audio openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups audio openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups audio openhabian [39;49;00m
+ usermod --append --groups audio openhabian
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*bluetooth:' /etc/group
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*dialout:' /etc/group
+ cond_redirect usermod --append --groups dialout openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups dialout openhab \033[39;49;00m'

[90;01m$ usermod --append --groups dialout openhab [39;49;00m
+ usermod --append --groups dialout openhab
+ return 0
+ cond_redirect usermod --append --groups dialout openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups dialout openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups dialout openhabian [39;49;00m
+ usermod --append --groups dialout openhabian
+ return 0
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*gpio:' /etc/group
+ for pGroup in "${groups[@]}"
+ grep -qs '^[[:space:]]*tty:' /etc/group
+ cond_redirect usermod --append --groups tty openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups tty openhab \033[39;49;00m'

[90;01m$ usermod --append --groups tty openhab [39;49;00m
+ usermod --append --groups tty openhab
+ return 0
+ cond_redirect usermod --append --groups tty openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups tty openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups tty openhabian [39;49;00m
+ usermod --append --groups tty openhabian
+ return 0
+ cond_redirect usermod --append --groups openhab openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ usermod --append --groups openhab openhabian \033[39;49;00m'

[90;01m$ usermod --append --groups openhab openhabian [39;49;00m
+ usermod --append --groups openhab openhabian
+ return 0
+ cond_redirect chown --silent openhab:openhab /srv /opt
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chown --silent openhab:openhab /srv /opt \033[39;49;00m'

[90;01m$ chown --silent openhab:openhab /srv /opt [39;49;00m
+ chown --silent openhab:openhab /srv /opt
+ return 0
+ cond_redirect chmod --silent ugo+w /srv
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chmod --silent ugo+w /srv \033[39;49;00m'

[90;01m$ chmod --silent ugo+w /srv [39;49;00m
+ chmod --silent ugo+w /srv
+ return 0
+ cond_redirect chown --recursive openhab:openhab /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chown --recursive openhab:openhab /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab \033[39;49;00m'

[90;01m$ chown --recursive openhab:openhab /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab [39;49;00m
+ chown --recursive openhab:openhab /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ return 0
+ cond_redirect chmod --recursive ug+wX /opt /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chmod --recursive ug+wX /opt /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab \033[39;49;00m'

[90;01m$ chmod --recursive ug+wX /opt /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab [39;49;00m
+ chmod --recursive ug+wX /opt /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ return 0
+ [[ -d /var/lib/openhab/.ssh ]]
+ cond_redirect chown --recursive openhabian:openhabian /home/openhabian
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chown --recursive openhabian:openhabian /home/openhabian \033[39;49;00m'

[90;01m$ chown --recursive openhabian:openhabian /home/openhabian [39;49;00m
+ chown --recursive openhabian:openhabian /home/openhabian
+ return 0
+ '[' -f /etc/mosquitto/passwd ']'
+ cond_redirect setfacl --recursive --remove-all /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ setfacl --recursive --remove-all /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab \033[39;49;00m'

[90;01m$ setfacl --recursive --remove-all /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab [39;49;00m
+ setfacl --recursive --remove-all /etc/openhab /var/lib/openhab /var/log/openhab /usr/share/openhab
+ return 0
+ cond_redirect chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba
+ [[ -n '' ]]
+ echo -e '\n\033[90;01m$ chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba \033[39;49;00m'

[90;01m$ chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba [39;49;00m
+ chgrp --silent root /var/log/samba /var/log/unattended-upgrades /opt/zram/log.bind/samba
+ return 1
+ echo 'FAILED (samba and 3rd party logdir)'
FAILED (samba and 3rd party logdir)
+ return 1
+ '[' 1 -ne 0 ']'
+ whiptail --msgbox 'There was an error or interruption during the execution of:\n  "10 | Apply Improvements"\n\nPlease try again. If the error persists, please read /opt/openhabian/docs/openhabian-DEBUG.md or https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md how to proceed.' 14 80
[?1049h[22;0;0t[1;63r[4l[?25l(B[m[37m[40m[1;63r[H[2J[1;1H[1m[37m[44m                                                                                                                                                                                                                                             [2;1H                                                                                                                                                                                                                                             [3;1H                                                                                                                                                                                                                                             [4;1H                                                                                                                                                                                                                                             [5;1H                                                                                                                                                                                                                                             [6;1H                                                                                                                                                                                                                                             [7;1H                                                                                                                                                                                                                                             [8;1H                                                                                                                                                                                                                                             [9;1H                                                                                                                                                                                                                                             [10;1H                                                                                                                                                                                                                                             [11;1H                                                                                                                                                                                                                                             [12;1H                                                                                                                                                                                                                                             [13;1H                                                                                                                                                                                                                                             [14;1H                                                                                                                                                                                                                                             [15;1H                                                                                                                                                                                                                                             [16;1H                                                                                                                                                                                                                                             [17;1H                                                                                                                                                                                                                                             [18;1H                                                                                                                                                                                                                                             [19;1H                                                                                                                                                                                                                                             [20;1H                                                                                                                                                                                                                                             [21;1H                                                                                                                                                                                                                                             [22;1H                                                                                                                                                                                                                                             [23;1H                                                                                                                                                                                                                                             [24;1H                                                                                                                                                                                                                                             [25;1H                                                                                                                                                                                                                                             [26;1H                                                                                                                                                                                                                                             [27;1H                                                                                                                                                                                                                                             [28;1H                                                                                                                                                                                                                                             [29;1H                                                                                                                                                                                                                                             [30;1H                                                                                                                                                                                                                                             [31;1H                                                                                                                                                                                                                                             [32;1H                                                                                                                                                                                                                                             [33;1H                                                                                                                                                                                                                                             [34;1H                                                                                                                                                                                                                                             [35;1H                                                                                                                                                                                                                                             [36;1H                                                                                                                                                                                                                                             [37;1H                                                                                                                                                                                                                                             [38;1H                                                                                                                                                                                                                                             [39;1H                                                                                                                                                                                                                                             [40;1H                                                                                                                                                                                                                                             [41;1H                                                                                                                                                                                                                                             [42;1H                                                                                                                                                                                                                                             [43;1H                                                                                                                                                                                                                                             [44;1H                                                                                                                                                                                                                                             [45;1H                                                                                                                                                                                                                                             [46;1H                                                                                                                                                                                                                                             [47;1H                                                                                                                                                                                                                                             [48;1H                                                                                                                                                                                                                                             [49;1H                                                                                                                                                                                                                                             [50;1H                                                                                                                                                                                                                                             [51;1H                                                                                                                                                                                                                                             [52;1H                                                                                                                                                                                                                                             [53;1H                                                                                                                                                                                                                                             [54;1H                                                                                                                                                                                                                                             [55;1H                                                                                                                                                                                                                                             [56;1H                                                                                                                                                                                                                                             [57;1H                                                                                                                                                                                                                                             [58;1H                                                                                                                                                                                                                                             [59;1H                                                                                                                                                                                                                                             [60;1H                                                                                                                                                                                                                                             [61;1H                                                                                                                                                                                                                                             [62;1H                                                                                                                                                                                                                                             [63;1H                                                                                                                                                                                                                                            [63;236H [4h [4l[1;1H[25;79H(B[m[30m[47m┌──────────────────────────────────────────────────────────────────────────────┐[26;79H│                                                                              │[1m[37m[40m [27;79H(B[m[30m[47m│ There was an error or interruption during the execution of:                  │[1m[37m[40m [28;79H(B[m[30m[47m│   "10 | Apply Improvements"                                                  │[1m[37m[40m [29;79H(B[m[30m[47m│                                                                              │[1m[37m[40m [30;79H(B[m[30m[47m│ Please try again. If the error persists, please read                         │[1m[37m[40m [31;79H(B[m[30m[47m│ /opt/openhabian/docs/openhabian-DEBUG.md or                                  │[1m[37m[40m [32;79H(B[m[30m[47m│ https://github.com/openhab/openhabian/blob/master/docs/openhabian-DEBUG.md   │[1m[37m[40m [33;79H(B[m[30m[47m│ how to proceed.                                                              │[1m[37m[40m [34;79H(B[m[30m[47m│                                                                              │[1m[37m[40m [35;79H(B[m[30m[47m│                                                                              │[1m[37m[40m [36;79H(B[m[30m[47m│                                    [37m[41m<Ok>[30m[47m                                      │[1m[37m[40m [37;79H(B[m[30m[47m│                                                                              │[1m[37m[40m [38;79H(B[m[30m[47m└──────────────────────────────────────────────────────────────────────────────┘[1m[37m[40m [39;80H                                                                                [36;117H[?12l[?25h[63;1H(B[m[37m[40m(B[m[39;49m
[K
```

**Comment by mstormi** [comment]
It fails because it's still the old code.

Note it is clonebranch=FixPerm**s**
When it asks you on startup to upgrade and select a branch, push Cancel.
or select the fixPerms branch in menu 01 before proceeding with menu 14

**Comment by juanhaywood** [comment]
Ok, now it runs without error, thanks!

However, after running, I'm still not able to access the shares. Is this a separate issue, or am I just doing something wrong?

![image](https://user-images.githubusercontent.com/53084642/103586950-e076d800-4eee-11eb-9184-751326ee5e3c.png)

**Comment by juanhaywood** [comment]
Just to add, thank you for all your help and time thus far. I really appreciate it.

If the above is something due to my own stupidity, I really apologise :S

**Comment by mstormi** [comment]
That's a different issue then.
Switch to openHAB3 branch now, I just merged the changes.
Try reinstalling Samba and ZRAM via menu.
