### ISSUE TITLE
No WiFi hotspot on installing openHabian

### ISSUE THREAD

**Issue by name-lake** [openhab/openhabian#1961]
When installing openHabian, no WiFi hotspot is created.
Actually, there is a similar issue “No WiFi hotspot on startup #1954” but it is closed. It seems I have the same error.

I installed the Openhabian version openHABian v1.9.5, file `openhabian-raspios64-latest-202501172059-crc3b16d562.img.xz` on Raspi 3 & Raspi 4.
The error is identical on both.
Since I'm not good at Linux, I wrote down the messages from the screen (& took photos).

My existing WiFi network was not recognized (that's another problem) & then the following screen messages came up:
```
- Setting up Network Manager und WiFi connection...Error: No network with SSID "XXXXX" found
- Ensuring network connectivity...FAILED
- Installing Comitup hotspot...
- Job for comitup.service failed because the control process exited with error code.
- See "sytemctl status comitup.service" and "journalctl -xeu comitup.service" for details.
- FAILED (comitup service not running)
- Installing Comitup hotspot...
- Job for comitup.service failed because the control process exited with error code.
- See "sytemctl status comitup.service" and "journalctl -xeu comitup.service" for details.
- OK
- The public internet is not reachable. Please check your local network environment.
  We have launched a publickly  accesible hotspot named openHabian-<n>.
  Use a device to connect and go to http://rasperrypi.local or http://10.41.0.1/ and select the WiFi network...
```
However there was no WiFi network named openHabian-n, surely because the comitup service was not running. So the message about the creation of the hotspot openHabian-n was not correct.

Result of `sytemctl status comitup.service`:

![Image](https://github.com/user-attachments/assets/231503e2-e31e-4c6f-bc0f-362bb33f0188)

Result of `journalctl -xeu comitup.service`:

![Image](https://github.com/user-attachments/assets/04debe71-7341-4b04-87c2-1a92aee004d0)

Hope I could help.

**Comment by mstormi** [comment]
I was able to reproduce it with a fresh install.
We need to install python3-networkmanager v2.2-3 from comitup repo

I'm not sure why it is missing.


```
root@testhouse:/boot# dpkg -l |grep networkmanager
ii  python3-networkmanager                           2.2-2                                     all          Python 3 interface to the NetworkManager D-Bus interface
```

Related: #1901

**Comment by mstormi** [comment]
Image doesn't build because of this change?
@ecdye any idea why?

https://github.com/openhab/openhabian/actions/runs/13101785099/job/36550922353#step:6:42

**Comment by mstormi** [comment]
There's something fundamentally bad @ecdye see #1964

**Comment by mstormi** [comment]
Fixed-By: #1967

@name-lake please try any recent build such as https://github.com/openhab/openhabian/actions/runs/13119469640
to confirm hotspot works again and let us know, thanks

**Comment by name-lake** [comment]
Hello mstormi,
thanks for the software named:
`openhabian-raspios64-latest-202502031801-crc28290563.img.xz`.
I tested it, unfortunately the comitup error is still there. No openHabian hotspot is created.
Enclosed, I think, the relevant photo:

![Image](https://github.com/user-attachments/assets/fe658499-677b-431a-9942-5ecc086e6304)

**Comment by mstormi** [comment]
Please try again with https://github.com/openhab/openhabian/releases/tag/v1.10.0

Please set debugmode=maximum in openhabian.conf before 1st boot

The screen output will also be in /boot/first-boot.log.

**Comment by mstormi** [comment]
Seems it's still the old version of comitup (1.38) that is being offline-installed during image creation.

We need to download the comitup and python3-networkmanager packages from the comitup author's repo instead to obtain a version that works.

**Comment by mstormi** [comment]
try the image from https://github.com/openhab/openhabian/actions/runs/13142838250
or wait for 1.10.1 then try with that

**Comment by mstormi** [comment]
> Run into same issue with v1.10.1

Are you sure it was 1.10.1? I've just started another build and it's correctly downloading and using the latest comitup packages and I believe I had seen that in 1.10.1, too.

**Comment by mstormi** [comment]
Try v1.10.2

**Comment by name-lake** [comment]
I would however I can not find v1.10.2 image?

**Comment by mstormi** [comment]
Now you should

**Comment by mstormi** [comment]
Please try again with `debugmode=maximum` set in `openhabian.conf` prior to first boot, then upload `/boot/first-boot.log` here.

**Comment by mstormi** [comment]
> Unfortunately it seems like there's still an issue with comitup.conf, which let the device boot in loop.


Cannot reproduce. 1.10.2 works fine for me, just a single reboot.
Fresh flash please. Set `debugmode=maximum`, I need to see where exactly it stops to see if it's really an issue or just cosmetic.
Can you retry please?

**Comment by mstormi** [comment]
No, the installation process is totally independent of the flash tool. You should keep using Raspi imager.
It'll also offer you the latest openHABian image by default so you don't have to search-download that upfront.
